// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: pkt.proto

package pkt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DemoPkt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source   uint32 `protobuf:"varint,1,opt,name=Source,proto3" json:"Source,omitempty"`
	Sequence uint64 `protobuf:"varint,2,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *DemoPkt) Reset() {
	*x = DemoPkt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoPkt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoPkt) ProtoMessage() {}

func (x *DemoPkt) ProtoReflect() protoreflect.Message {
	mi := &file_pkt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoPkt.ProtoReflect.Descriptor instead.
func (*DemoPkt) Descriptor() ([]byte, []int) {
	return file_pkt_proto_rawDescGZIP(), []int{0}
}

func (x *DemoPkt) GetSource() uint32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *DemoPkt) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DemoPkt) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkt_proto protoreflect.FileDescriptor

var file_pkt_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x6b, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x6b, 0x74,
	0x22, 0x51, 0x0a, 0x07, 0x44, 0x65, 0x6d, 0x6f, 0x50, 0x6b, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x42, 0x13, 0x5a, 0x11, 0x6a, 0x69, 0x6e, 0x76, 0x2f, 0x6b, 0x69, 0x6d, 0x2f,
	0x77, 0x69, 0x72, 0x65, 0x3b, 0x70, 0x6b, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkt_proto_rawDescOnce sync.Once
	file_pkt_proto_rawDescData = file_pkt_proto_rawDesc
)

func file_pkt_proto_rawDescGZIP() []byte {
	file_pkt_proto_rawDescOnce.Do(func() {
		file_pkt_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkt_proto_rawDescData)
	})
	return file_pkt_proto_rawDescData
}

var file_pkt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkt_proto_goTypes = []interface{}{
	(*DemoPkt)(nil), // 0: pkt.DemoPkt
}
var file_pkt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkt_proto_init() }
func file_pkt_proto_init() {
	if File_pkt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoPkt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkt_proto_goTypes,
		DependencyIndexes: file_pkt_proto_depIdxs,
		MessageInfos:      file_pkt_proto_msgTypes,
	}.Build()
	File_pkt_proto = out.File
	file_pkt_proto_rawDesc = nil
	file_pkt_proto_goTypes = nil
	file_pkt_proto_depIdxs = nil
}
